
openapi: 3.0.0
info:
  title: S3 Backend Service API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /upload:
    post:
      summary: Upload a file to S3
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
        '400':
          description: Bad request

  /files/{fileName}:
    get:
      summary: Download a file from S3
      parameters:
        - in: path
          name: fileName
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File retrieved successfully
        '404':
          description: File not found

    put:
      summary: Update an existing file in S3
      parameters:
        - in: path
          name: fileName
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File updated successfully
        '400':
          description: Bad request

    delete:
      summary: Delete a file from S3
      parameters:
        - in: path
          name: fileName
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File deleted successfully
        '404':
          description: File not found
