
openapi: 3.0.0
info:
  title: S3 Backend Service API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload a file to S3
      # Define request and response schema
  # Define other CRUD operations
